// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// initVals
List initVals(NumericMatrix Z, arma::colvec Yr, float mincor);
RcppExport SEXP _SEMMS_initVals(SEXP ZSEXP, SEXP YrSEXP, SEXP mincorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< float >::type mincor(mincorSEXP);
    rcpp_result_gen = Rcpp::wrap(initVals(Z, Yr, mincor));
    return rcpp_result_gen;
END_RCPP
}
// GAMupdate
List GAMupdate(IntegerVector initidx, IntegerVector initval, arma::colvec Yr, NumericMatrix Xr, NumericMatrix Z, char distr, bool randomize, double mincor, int maxsteps, double minchange, bool ptf);
RcppExport SEXP _SEMMS_GAMupdate(SEXP initidxSEXP, SEXP initvalSEXP, SEXP YrSEXP, SEXP XrSEXP, SEXP ZSEXP, SEXP distrSEXP, SEXP randomizeSEXP, SEXP mincorSEXP, SEXP maxstepsSEXP, SEXP minchangeSEXP, SEXP ptfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type initidx(initidxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type initval(initvalSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< char >::type distr(distrSEXP);
    Rcpp::traits::input_parameter< bool >::type randomize(randomizeSEXP);
    Rcpp::traits::input_parameter< double >::type mincor(mincorSEXP);
    Rcpp::traits::input_parameter< int >::type maxsteps(maxstepsSEXP);
    Rcpp::traits::input_parameter< double >::type minchange(minchangeSEXP);
    Rcpp::traits::input_parameter< bool >::type ptf(ptfSEXP);
    rcpp_result_gen = Rcpp::wrap(GAMupdate(initidx, initval, Yr, Xr, Z, distr, randomize, mincor, maxsteps, minchange, ptf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SEMMS_initVals", (DL_FUNC) &_SEMMS_initVals, 3},
    {"_SEMMS_GAMupdate", (DL_FUNC) &_SEMMS_GAMupdate, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_SEMMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
