# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initVals <- function(Z, Yr, mincor = 0.7) {
    .Call('_SEMMS_initVals', PACKAGE = 'SEMMS', Z, Yr, mincor)
}

GAMupdate <- function(initidx, initval, Yr, Xr, Z, distr = 'N', randomize = TRUE, mincor = 0.7, maxsteps = 20L, minchange = 1, ptf = TRUE) {
    .Call('_SEMMS_GAMupdate', PACKAGE = 'SEMMS', initidx, initval, Yr, Xr, Z, distr, randomize, mincor, maxsteps, minchange, ptf)
}

