# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get an initial set of putative variables for the GAM algorithm
#'
#' @param Z matrix of putative variables
#' @param Yr the (possibly transformed) response
#' @param mincor a threshold of (absolute) correlation above which a pair is considered highly correlated
#' @return a list with elements: \code{discard} (integer vector; for each
#'   variable, the index of the variable it is correlated with and therefore
#'   discarded in favour of, or -1 if kept) and \code{beta} (numeric vector of
#'   simple linear regression coefficients, one per column of Z).
initVals <- function(Z, Yr, mincor = 0.7) {
    .Call('_SEMMS_initVals', PACKAGE = 'SEMMS', Z, Yr, mincor)
}

#' Run the GAM algorithm to select non-null variables
#'
#' @param initidx an initial set of variables to use in the fitting algorithm
#' @param initval the values (-1 or 1) of the initial set of predictors
#' @param Yr the response vector
#' @param Xr the fixed-effect design matrix
#' @param Z the matrix of all putative variables
#' @param distr the GLM distribution to fit (N=Normal, B=binary, P=Poisson)
#' @param randomize Boolean - whether to run the greedy or randomized version
#' @param mincor a threshold of (absolute) correlation above which a pair is considered highly correlated
#' @param maxsteps maximum number of GAM iterations
#' @param minchange the minimum difference in log-likelihood between consecutive iterations below which we assume that the algorithm has converged
#' @param ptf Boolean - whether to print debug messages to SEMMS.log
#' @return a list with elements: \code{nn} (1-based integer indices of selected
#'   non-null variables), \code{mu} (mixture mean), \code{beta} (mixture
#'   regression coefficients), \code{s2r} (random-effect variance), \code{s2e}
#'   (residual variance), \code{gam_nn} (sign, +/-1, of the effect of each
#'   selected variable), \code{pp} (matrix of posterior probabilities), and
#'   \code{lockedOut} (integer vector indicating variables excluded because they
#'   are highly correlated with a selected variable; non-zero value = index of
#'   the selected variable they are correlated with).
GAMupdate <- function(initidx, initval, Yr, Xr, Z, distr = 'N', randomize = TRUE, mincor = 0.7, maxsteps = 20L, minchange = 1, ptf = TRUE) {
    .Call('_SEMMS_GAMupdate', PACKAGE = 'SEMMS', initidx, initval, Yr, Xr, Z, distr, randomize, mincor, maxsteps, minchange, ptf)
}

